export const JobsData = [
	{
        name: 'Eniola Lucas',
        role: 'Applicant',
        status: 'upcoming',
        title: 'Professional Grass Cutter',
        date: 'Tuesday 3rd March, 2024',
        time:'9:00 AM.',
        duration:'2hrs',
		amount:'5000',
        worker: 'Gabriel John',
		image: 'profile.png',
		location: '4517 Washington Ave. Manchester, Kentucky 39495, Ilorin Nigeria',
	},
	{
        name: 'Eniola Lucas',
        role: 'Applicant',
        status: 'ongoing',
        title: 'Professional Grass Cutter',
        date: 'Monday 2nd March, 2024',
        time:'9:00 AM.',
        duration:'2hrs',
		amount:'4000',
        worker: 'Mathem Ahmed',
		image: 'profile.png',
		location: '4517 Washington Ave. Manchester, Kentucky 39495, Ilorin Nigeria',
	},
	{
       name: 'Eniola Lucas',
        role: 'Applicant',
        status: 'completed',
        title: 'Professional Grass Cutter',
        date: 'Monday 6th January, 2025',
        time:'9:00 AM.',
        duration:'2hrs',
		amount:'4000',
        worker: 'Mary Dan',
		image: 'profile.png',
		location: '4517 Washington Ave. Manchester, Kentucky 39495, Ilorin Nigeria',
	},
	{
        name: 'Eniola Lucas',
        role: 'Applicant',
        status: 'canceled',
        title: 'Professional Grass Cutter',
        date: 'Monday 2nd March, 2024',
        time:'9:00 AM.',
        duration:'2hrs',
		amount:'4000',
        worker: 'Musa Blessing',
		image: 'profile.png',
		location: '4517 Washington Ave. Manchester, Kentucky 39495, Ilorin Nigeria',
	},


]